name: reservarosario
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.1
  
  # State Management
  provider: ^6.1.2
  
  # Supabase
  supabase_flutter: ^2.8.0
  
  # UI Components
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8
  
  # Animaciones modernas 2025
  animate_do: ^4.2.0
  lottie: ^3.1.3
  flutter_staggered_animations: ^1.1.1
  rive: ^0.13.19
  
  # Calendario moderno Material 3
  table_calendar: ^3.1.2
  
  # Navigation
  go_router: ^16.3.0
  
  
  # Utilities
  uuid: ^4.5.1
  http: ^1.2.2
  shared_preferences: ^2.3.3
  
  # Image handling
  image_picker: ^1.1.2
  
  # Location
  geolocator: ^13.0.2
  
  # Permissions
  permission_handler: ^11.3.1
  
  # WhatsApp integration
  url_launcher: ^6.3.1
  
  # Firebase
  firebase_core: ^4.2.0
  firebase_analytics: ^12.0.3
  firebase_auth: ^6.1.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
