// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvpiId-73FKMpUTT8rD74j7gxkLKGN75s',
    appId: '1:719825636821:web:086a89b95080a4dee5415c',
    messagingSenderId: '719825636821',
    projectId: 'sodita-314e6',
    authDomain: 'sodita-314e6.firebaseapp.com',
    storageBucket: 'sodita-314e6.firebasestorage.app',
    measurementId: 'G-3WRDHD67FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvpiId-73FKMpUTT8rD74j7gxkLKGN75s',
    appId: '1:719825636821:android:086a89b95080a4dee5415c',
    messagingSenderId: '719825636821',
    projectId: 'sodita-314e6',
    authDomain: 'sodita-314e6.firebaseapp.com',
    storageBucket: 'sodita-314e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvpiId-73FKMpUTT8rD74j7gxkLKGN75s',
    appId: '1:719825636821:ios:086a89b95080a4dee5415c',
    messagingSenderId: '719825636821',
    projectId: 'sodita-314e6',
    authDomain: 'sodita-314e6.firebaseapp.com',
    storageBucket: 'sodita-314e6.firebasestorage.app',
    iosClientId: '719825636821-example.googleusercontent.com',
    iosBundleId: 'com.example.reservarosario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvpiId-73FKMpUTT8rD74j7gxkLKGN75s',
    appId: '1:719825636821:ios:086a89b95080a4dee5415c',
    messagingSenderId: '719825636821',
    projectId: 'sodita-314e6',
    authDomain: 'sodita-314e6.firebaseapp.com',
    storageBucket: 'sodita-314e6.firebasestorage.app',
    iosClientId: '719825636821-example.googleusercontent.com',
    iosBundleId: 'com.example.reservarosario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvpiId-73FKMpUTT8rD74j7gxkLKGN75s',
    appId: '1:719825636821:web:086a89b95080a4dee5415c',
    messagingSenderId: '719825636821',
    projectId: 'sodita-314e6',
    authDomain: 'sodita-314e6.firebaseapp.com',
    storageBucket: 'sodita-314e6.firebasestorage.app',
    measurementId: 'G-3WRDHD67FP',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDvpiId-73FKMpUTT8rD74j7gxkLKGN75s',
    appId: '1:719825636821:web:086a89b95080a4dee5415c',
    messagingSenderId: '719825636821',
    projectId: 'sodita-314e6',
    authDomain: 'sodita-314e6.firebaseapp.com',
    storageBucket: 'sodita-314e6.firebasestorage.app',
    measurementId: 'G-3WRDHD67FP',
  );
}